#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.

# Path to the hosts file
hosts_file="/etc/hosts"

# Backup the original hosts file
sudo cp $hosts_file "${hosts_file}.bak"

# Adding entries to the hosts file
echo "127.0.0.2 localhost" | sudo tee -a $hosts_file
echo "8.8.8.8 facebook.com" | sudo tee -a $hosts_file

echo "Configuration completed. /etc/hosts has been updated."